// Generated by Wrangler on Tue Aug 26 2025 15:48:04 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
        GITHUB_CLIENT_ID: "Ov23liMHgyLkKUcMYwsj";
        GITHUB_CLIENT_SECRET: string;
}
