// Generated by Wrangler on Tue Aug 26 2025 15:48:04 GMT+0000 (Coordinated Universal Time)
// by running `wrangler types`

interface Env {
        GITHUB_OAUTH_ID: "Ov23lip0IFnhLG0yv9Mn";
        GITHUB_OAUTH_SECRET: string;
}
