name = "decap-proxy"
main = "src/index.ts"
compatibility_date = "2024-06-01"

routes = [
  { pattern = "decap.eighthwayministries.org/auth*", zone_name = "eighthwayministries.org" },
  { pattern = "decap.eighthwayministries.org/callback*", zone_name = "eighthwayministries.org" }
]

[vars]
# You can also set these in the dashboard if you prefer
# GITHUB_CLIENT_ID = "..."
# GITHUB_CLIENT_SECRET = "..."
